# Generated by Django 4.2.26 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_location', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('loc_lat', models.FloatField()),
                ('loc_lng', models.FloatField()),
                ('total_carpet_area', models.FloatField()),
                ('flat_total', models.IntegerField()),
                ('shop_total', models.IntegerField()),
                ('office_total', models.IntegerField()),
                ('others_total', models.IntegerField()),
            ],
        ),
    ]
