# Generated by Django 4.2.26 on 2025-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
